name: air_monitor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  get_storage: ^2.1.1
  lottie: ^2.4.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  geolocator: ^9.0.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/
  uses-material-design: true
